eyuOps/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from owgame.views import base
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^$',base,name='base'),
    url(r'^admin/', admin.site.urls),
    url(r'^ow/',include('owgame.urls',namespace="ow")),
]

owgame/urls.py
# /usr/bin/python
#coding:utf-8

__Date__ = "2016-10-21 11:26"
__Author__ = 'eyu Fanne'

from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$',views.index,name='index'),

    ##数据库查询
    url(r'Hw_Formal_Owgame_SqlQuery/',views.Hw_Formal_Owgame_SqlQuery,name='Hw_Formal_Owgame_SqlQuery'),
    url(r'HW_Cross_sqlQuery/',views.HW_Cross_sqlQuery,name='HW_Cross_sqlQuery'),
    url(r'HW_Server_Test_sqlQuery/',views.HW_Server_Test_sqlQuery,name='HW_Server_Test_sqlQuery'),
    url(r'GN_Server_Test_sqlQuery/',views.GN_Server_Test_sqlQuery,name='GN_Server_Test_sqlQuery'),

    ##版本更新
    url(r'Hw_Formal_Owgame_Update/',views.Hw_Formal_Owgame_Update,name='Hw_Formal_Owgame_Update'),

    ##打补丁
    url(r'patch/',views.patch,name='patch'),

    ##初始化服务器
    url(r'initServer/',views.initServer,name='initServer'),

    ##添加新服
    url(r'addServer/',views.addServer,name='addServer'),
]

owgame/models.py
#coding:utf-8
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_delete
from django.dispatch import receiver

# Create your models here.


class owgameserver(models.Model):
    serverid = models.IntegerField(u"游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"游戏服IP")
    servername = models.CharField(u"游戏服名称",max_length=32)
    serverport = models.IntegerField(u"游戏服端口号")
    addstatus = models.IntegerField(u"开服状态",default=0) ##0:表示未在生产环境添加新服，1：代表已在生产环境添加新服

    def __unicode__(self):
        return self.servername


##海外游戏服正式服
class hw_formal_owgame(models.Model):
    serverid = models.IntegerField(u"海外正式服_游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"海外正式服_游戏服IP")
    servername = models.CharField(u"海外正式服_游戏服服名称",max_length=16)
    serverport = models.IntegerField(u"海外正式服_游戏服端口号")
    addstatus = models.IntegerField(u"开服状态",default=0) ##0:表示未在生产环境添加新服，1：代表已在生产环境添加新服

    def __unicode__(self):
        return self.servername

##海外游戏服测试服
class hw_test_owgame(models.Model):
    serverid = models.IntegerField(u"海外测试服_游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"海外测试服_游戏服IP")
    servername = models.CharField(u"海外测试服_游戏服服名称",max_length=16)
    serverport = models.IntegerField(u"海外测试服_游戏服端口号")

    def __unicode__(self):
        return self.servername



##海外游戏服审核服
class hw_audit_owgame(models.Model):
    serverid = models.IntegerField(u"海外审核服_游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"海外审核服_游戏服IP")
    servername = models.CharField(u"海外审核服_游戏服服名称",max_length=16)
    serverport = models.IntegerField(u"海外审核服_游戏服端口号")

    def __unicode__(self):
        return self.servername


##海外充值服正式服
class hw_formal_owcharge(models.Model):
    pass


##海外充值服测试服
class hw_test_owcharge(models.Model):
    pass




##海外跨服正式服
class hw_formal_owcross(models.Model):
    pass



class gn_test_owgameserver(models.Model):
    serverid = models.IntegerField(u"游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"游戏服IP")
    servername = models.CharField(u"游戏服名称",max_length=16)
    serverport = models.IntegerField(u"游戏服端口号")

    def __unicode__(self):
        return self.servername


##海外礼包序列服
class hw_owgift(models.Model):
    pass


##国内游戏服测试服
class gn_test_owgame(models.Model):
    serverid = models.IntegerField(u"国内测试服_游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"国内测试服_游戏服IP")
    servername = models.CharField(u"国内测试服_游戏服服名称",max_length=16)
    serverport = models.IntegerField(u"国内测试服_游戏服端口号")

    def __unicode__(self):
        return self.servername

##国内审核服
class gn_audit_owgame(models.Model):
    serverid = models.IntegerField(u"国内审核服_游戏服ID号",primary_key=True)
    serverhost = models.GenericIPAddressField(u"国内审核服_游戏服IP")
    servername = models.CharField(u"国内审核服_游戏服服名称",max_length=16)
    serverport = models.IntegerField(u"国内审核服_游戏服端口号")

    def __unicode__(self):
        return self.servername

owgame/forms.py
# /usr/bin/python
#coding:utf-8

__Date__ = "2016-11-18 11:30"
__Author__ = 'eyu Fanne'

from django import forms

class SqlQueryForm(forms.Form):
    SqlCmd = forms.CharField(label='SqlQuery',max_length=100)


class AddServerForm(forms.Form):
    AddNum = forms.IntegerField(label='AddServer')

class VersionForm(forms.Form):
    version = forms.IntegerField(label="Version Num")

owgame/views.py
#coding:utf-8
from __future__ import absolute_import, unicode_literals
from django.http import HttpResponse
from django.shortcuts import render_to_response,render,redirect
from django.core.urlresolvers import reverse
from django.contrib import messages

# from models import hw_formal_owgame
from owgame.models import hw_formal_owgame
from owgame.forms import SqlQueryForm,AddServerForm,VersionForm
from owgame.sqlquery import runSql
from owgame.tasks import pingTest,NewServer

import collections


# Create your views here.

def base(request):
    return render_to_response('base.html')


def index(request):
    return render_to_response('owindex.html')

    # return HttpResponse("The index Page")


def Hw_Formal_Owgame_SqlQuery(request):
    owdbList = hw_formal_owgame.objects.all()
    if request.method == 'POST':
        form = SqlQueryForm(request.POST)
        if form.is_valid():
            serverlist = request.POST.getlist("dbcheckbox")
            request.session['SqlCmd'] = form.cleaned_data['SqlCmd']
            if serverlist == []:
                messages.add_message(request, messages.INFO, u'未勾选游戏服')
                return redirect('owgame.views.Hw_Formal_Owgame_SqlQuery')
            else:

                request.session['indexsql'] = {}
                for server_i in serverlist:
                    dbsql = hw_formal_owgame.objects.filter(pk=server_i)
                    dbhost = dbsql[0].serverhost
                    request.session['dbname'] = dbsql[0].servername
                    request.session['sqlres']=runSql(dbhost,server_i,request.session['SqlCmd'])
                    request.session['indexsql'][server_i] = request.session['sqlres']
                messages.add_message(request, messages.INFO, u'数据库查询完成')
                request.session['sqldic'] = collections.OrderedDict(sorted(request.session['indexsql'].items(), key=lambda x: x[0]))
            return redirect('owgame.views.Hw_Formal_Owgame_SqlQuery')
    else:
        form = SqlQueryForm()
    return render(request,'Hw_Formal_Owgame_SqlQuery.html',
                  {
                      'owdbList':owdbList,
                      'form':form,
                      'SqlCmd':request.session.get('SqlCmd'),
                      'sqldic':request.session.get('sqldic'),
                      'dbname':request.session.get('dbname'),
                  }
    )




def HW_Cross_sqlQuery(request):
    return render_to_response('HW_Cross_sqlQuery.html')

def HW_Server_Test_sqlQuery(request):
    return render_to_response('HW_Server_Test_sqlQuery.html')

def GN_Server_Test_sqlQuery(request):
    return render_to_response('GN_Server_Test_sqlQuery.html')



##海外正式服更新
def Hw_Formal_Owgame_Update(request):
    # versionform = VersionForm()
    # if versionform.validate_on_submit():
    #     request.session['proId'] = request.form.get('selectid')
    #     request.session['versionNum'] = versionform.version.data
    #     proId = request.session.get('proId')
    #     versionNum = request.session.get('versionNum')
    #
    #     # app = current_app._get_current_object()
    #     # startRsync(app,proDic,proId,versionNum)
    #     return redirect('owgame.views.Hw_Formal_Owgame_Update')
    # return render_to_response('Hw_Formal_Owgame_Update.html',
    #                        prodict = pronameDict(),
    #                        versionform = versionform)

    return render_to_response("Hw_Formal_Owgame_Update.html")


def patch(request):
    return HttpResponse('This is patch Page')


def initServer(request):
    return render_to_response('initServer.html')


def addServer(request):
    if request.method == "POST":
        addserverfrom = AddServerForm(request.POST)
        if addserverfrom.is_valid():
            serverid = addserverfrom.cleaned_data['AddNum']
            # pingTest.delay(serverid)

            ##异步添加新服
            NewServer.delay(serverid)


        return redirect('owgame.views.addServer')

    else:
        addserverfrom = AddServerForm()

    return render(request,'addServer.html',
        {
              "addserverfrom":addserverfrom,
        }
    )

TestAjax/templates/my01.html
<!DOCTYPE html>
<html>
<head>
<script src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js">
</script>
<script>
$(document).ready(function(){
  $("#btn1").click(function(){
    $('#test').load('static/2d33.txt',function(responseTxt,statusTxt,xhr){
        if(statusTxt=="success")
            alert("成功");
        if(statusTxt=="error")
            alert("Error: "+xhr.status+": "+xhr.statusText);
    });

  })
})
</script>
</head>

<body>

<h3 id="test">请点击下面的按钮，通过 jQuery AJAX 改变这段文本。</h3>
<button id="btn1" type="button">获得外部的内容</button>

</body>
</html>

TestAjax/templates/postTest.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>jquery ajax的post功能测试</title>
    <script src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
    <script>
    $(document).ready(function(){
        $("#btn13").click(function(){
            console.log("ddddddd");
            alert("weeweww");
        });
    });
    </script>


</head>

<body>
<h3>jquery ajax的post功能测试</h3>
<form method="POST" id="mypost">
<p>名字：</p>
<input type="text" name="name" id="name"><br>
<p>年龄：</p>
<input type="text" name="age" id="age"><br><br>
<input type="submit" value="Submit" id="btn13">
</form>
</body>

</html>

TestAjax/templates/test01.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>

    <script src="http://apps.bdimg.com/libs/jquery/1.9.1/jquery.js"></script>
    <script>
    $(document).ready(function(){
       $("#ajaxform").submit(function(e)
{
	var postData = $(this).serializeArray();
	var formURL = $(this).attr("action");
	$.ajax(
	{
		url : "test01",
		type: "POST",
		data : postData,
		success:function(data, textStatus, jqXHR)
		{
            alter(data,textStatus)

		},
		error: function(jqXHR, textStatus, errorThrown)
		{
		}
	});
    e.preventDefault();	//STOP default action
});

$("#ajaxform").submit(); //SUBMIT FORM
    });
    </script>

</head>
<body>
<form name="ajaxform" id="ajaxform" action="/test01" method="POST">
    First Name: <input type="text" name="fname" value =""/> <br/>
    Last Name: <input type="text" name="lname" value ="" /> <br/>
    Email : <input type="text" name="email" value=""/> <br/>
    <input type="submit" value="submit">
</form>
</body>
</html>

TestAjax/templates/test02.html
<!DOCTYPE html>
 <html lang="en">
 
 <head>
     <meta charset="utf-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta name="description" content="">
     <meta name="author" content="">
     <link rel="icon" href="../../favicon.ico">
 
     <title>Signin Template for Bootstrap </title>
 
     <!-- Bootstrap core CSS -->
     <link href="static/css/bootstrap.min.css" rel="stylesheet">
 
     <!-- Custom styles for this template -->
     <link href="static/css/signin.css" rel="stylesheet">
 
     <script src="static/js/jquery-1.9.0.js"> </script>
 
 </head>
 
 <body>
 
     <div class="container">
 
         <form class="form-signin" action="/signUp" method="post" role="form">
             <h2 class="form-signin-heading">Please Sign Up </h2>
             <input type="email" name="username" class="form-control" placeholder="Email address" required autofocus>
             <input type="password" name="password" class="form-control" placeholder="Password" required>
 
             <button class="btn btn-lg btn-primary btn-block" type="button">Register </button>
         </form>
      
     </div>
   
 </body>
 
 </html>

owgame/templates/GN_Server_Test_sqlQuery.html
{% extends "owindex.html" %}
{% block page %}
<div class="container">
<h3><center><font color="blue">海外游戏正式服数据查询</font></center></h3></div>
<div class="container">
  <div class="row">
    <form role="form" id="contact-form" class="contact-form">
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="Name"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="Message"></textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <button type="submit" class="btn main-btn pull-right">Send a message</button></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

owgame/templates/HW_Cross_sqlQuery.html
{% extends "owindex.html" %}
{% block page %}
<div class="container">
<h3><center><font color="green">海外游戏正式服数据查询</font></center></h3></div>
<div class="container">
  <div class="row">
    <form role="form" id="contact-form" class="contact-form">
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="Name"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="Message"></textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <button type="submit" class="btn main-btn pull-right">Send a message</button></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

owgame/templates/HW_Server_Test_sqlQuery.html
{% extends "owindex.html" %}
{% block page %}
<div class="container">
<h3><center>海外游戏测试服数据查询</center></h3>
</div>
<div class="container">
  <div class="row">
    <form role="form" id="contact-form" class="contact-form">
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="Name"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="Message"></textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <button type="submit" class="btn main-btn pull-right">Send a message</button></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

owgame/templates/HW_Server_sqlQuery.html
{% extends "owindex.html" %}
{% block page %}
<div class="container">
    <h3>
        <center>
            <font color="red">
                海外游戏正式服数据查询 这是个测试文件，后期删除
            </font>
        </center>
    </h3>
</div>
<br><br>

<div class="container">
    <div class="row">
        <form role="form" id="contact-form" class="contact-form">
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <div class="checkbox checkbox-inline checkbox-info">
                            <input type="checkbox" class="styled" id="inlineCheckbox1" value="option1">
                            <label for="inlineCheckbox1">
                                选项1
                            </label>
                        </div>
                        <div class="checkbox checkbox-inline checkbox-info">
                            <input type="checkbox" class="styled" id="inlineCheckbox2" value="option2">
                            <label for="inlineCheckbox2">
                                选项2
                            </label>
                        </div>
                        <br><br>

                        <input type="button" value="全选" class="btn" id="selectAll">
                        <input type="button" value="全不选" class="btn" id="unSelect">
                        <input type="button" value="反选" class="btn" id="reverse">
                        <input type="button" value="获得选中的所有值" class="btn" id="getValue">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <textarea class="form-control textarea" rows="3" name="Message" id="Message"
                        placeholder="Message">
                        </textarea>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <button type="submit" class="btn main-btn pull-right">
                        Send a message
                    </button>
                </div>
            </div>
        </form>
    </div>
<div>

{% endblock %}

owgame/templates/Hw_Formal_Owgame_Update.html
{% extends "owindex.html" %}
{% block page %}
<div class="container">
<h3><center>海外游戏测试服数据查询</center></h3>
</div>
<div class="container">
  <div class="row">
    <form role="form" id="contact-form" class="contact-form">
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="Name"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            <textarea class="form-control textarea" rows="3" name="Message" id="Message" placeholder="Message"></textarea>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <button type="submit" class="btn main-btn pull-right">Send a message</button></div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

owgame/templates/addServer.html
{% extends "owindex.html" %}
{% load myfilters %}
{% block page %}
<div class="container">
{% if messages %}
        <div class="alert alert-warning">
            {% for message in messages %}
            <p>
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message}}
            </p>
            {% endfor %}
        </div>
        {% endif %}
<h3><center>添加新服</center></h3>
</div>
<br>
<div class="container">
  <div class="row">
    <form role="form" id="addserver-form" class="contact-form" method="post">
    {% csrf_token  %}
      <div class="row">
        <div class="col-md-12">
          <div class="form-group">
            {{ addserverfrom.AddNum|add_class:"form-control" }}
            <br>
            <button type="submit" class="btn main-btn pull-right" id="addserverform">Add a NewServer</button>
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock %}

owgame/templates/owindex.html
{% extends "base.html" %}

{% block content %}
<div class="row affix-row">
    <div class="col-sm-3 col-md-2 affix-sidebar">
        <div class="sidebar-nav">
            <div class="navbar navbar-default" role="navigation">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
                        <span class="sr-only">
                            Toggle navigation
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                        <span class="icon-bar">
                        </span>
                    </button>
                    <span class="visible-xs navbar-brand">
                        Sidebar menu
                    </span>
                </div>
                <div class="navbar-collapse collapse sidebar-navbar-collapse">
                    <ul class="nav navbar-nav" id="sidenav01">
                        <li class="active">
                            <a href="#" data-toggle="collapse" data-target="#toggleDemo0" data-parent="#sidenav01"
                            class="collapsed">
                                <h4>
                                    控制面板
                                </h4>
                            </a>
                        </li>
                        <li>
                            <a href="#" data-toggle="collapse" data-target="#toggleDemo" data-parent="#sidenav01"
                            class="collapsed">
                                <span class="glyphicon glyphicon-cloud">
                                </span>
                                数据查询
                                <span class="caret pull-right">
                                </span>
                            </a>
                            <div class="collapse" id="toggleDemo" style="height: 0px;">
                                <ul class="nav nav-list">
                                    <li>
                                        <a href="{% url 'ow:Hw_Formal_Owgame_SqlQuery' %}">
                                            海外正式游戏服
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'ow:HW_Cross_sqlQuery' %}">
                                            海外正式跨服
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'ow:HW_Server_Test_sqlQuery' %}">
                                            海外测试服
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'ow:GN_Server_Test_sqlQuery' %}">
                                            国内测试服
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#" data-toggle="collapse" data-target="#toggleDemo2" data-parent="#sidenav01"
                            class="collapsed">
                                <span class="glyphicon glyphicon-inbox">
                                </span>
                                执行补丁操作
                                <span class="caret pull-right">
                                </span>
                            </a>
                            <div class="collapse" id="toggleDemo2" style="height: 0px;">
                                <ul class="nav nav-list">
                                    <li>
                                        <a href="#">
                                            海外正式游戏服
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            海外正式全服
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            海外正式跨服
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="#" data-toggle="collapse" data-target="#toggleDemo3" data-parent="#sidenav01"
                            class="collapsed">
                                <span class="glyphicon glyphicon-download-alt">
                                </span>
                                版本更新
                                <span class="caret pull-right">
                                </span>
                            </a>
                            <div class="collapse" id="toggleDemo3" style="height: 0px;">
                                <ul class="nav nav-list">
                                    <li>
                                        <a href="{% url 'ow:Hw_Formal_Owgame_Update' %}">
                                            海外正式服更新
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            海外测试服全服更新
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            国内测试服更新
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li>
                            <a href="{% url 'ow:initServer' %}">
                                <span class="glyphicon glyphicon-tasks">
                                </span>
                                服务器初始化
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'ow:addServer' %}">
                                <span class="glyphicon glyphicon-saved">
                                </span>
                                添加新服
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="glyphicon glyphicon-calendar">
                                </span>
                                WithBadges
                                <span class="badge pull-right">
                                    42
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="">
                                <span class="glyphicon glyphicon-cog">
                                </span>
                                PreferencesMenu
                            </a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>
    </div>

{% endblock content %}


{% block page %}
<p>hhhhhh</p>
{% endblock %}

templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eyu Game Ops</title>
    <!-- Bootstrap -->
    <!-- <link href="static/css/bootstrap.min.css" rel="stylesheet">
    -->{% load staticfiles %}
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/font-awesome.min.css" %}" rel="stylesheet">
    <link href="{% static "css/awesome-bootstrap-checkbox.css" %}" rel="stylesheet">
    <!-- <link href="static/css/base.css" rel="stylesheet">
    -->
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]--></head>

  <body>
    <nav class="navbar navbar-default navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'base' %}">EyuGame Ops</a></div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li>
              <a href="{% url 'ow:index'%}">OW项目</a></li>
            <li>
              <a href="#">BOP项目</a></li>
            <li>
              <a href="#">爱西游项目</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="buttun">
              <a href=/admin>
                <b>Admin</b>
              </a>
            </li>
          </ul>
        </div>
        <!-- /.navbar-collapse --></div>
      <!-- /.container-fluid --></nav>{% block content %}{% endblock %}
    <div class="affix-content">
      <div class="container ">
        <div class="page-header">
          <h3>
            <span class="glyphicon glyphicon-th-list"></span>Navigation</h3></div>{% block page %}
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris lectus orci, viverra nec neque non, tincidunt commodo leo. Nullam eleifend velit purus, id aliquam elit venenatis sit amet. Cras vel nisl eget eros tempus viverra. Phasellus in enim et nulla tempor blandit. Donec at lectus sit amet velit faucibus tincidunt quis sed est. Mauris placerat purus odio. In egestas, velit quis congue sodales, turpis lacus pellentesque neque, quis accumsan orci nibh sed mauris. Sed sit amet pulvinar felis. Aliquam consequat tellus non ligula elementum, at egestas quam vestibulum. {% endblock page %}</div>
    </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <!-- <script src="static/js/jquery.min.js"></script>
    -->
    <script src="{% static "js/jquery.min.js" %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="static/js/bootstrap.min.js"></script>
    -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "js/ow.js" %}"></script>
    <script src="{% static "js/clipboard.js" %}" type="text/javascript"></script>

    <script>
    var clipboard = new Clipboard('.btn');

    clipboard.on('success', function(e) {
    	alert("文字已复制到剪贴板中");
        console.log(e);
    });

    clipboard.on('error', function(e) {
        console.log(e);
    });
    </script>
  </body>

</html>